<?php

	/* Spanish language configuration */
	 $lang = array (
		'errorPermisos' => "No tiene permisos para acceder a este área",
		'accesoIncorrecto' => "Error - Acceso incorrecto!",		
	 	'seguro' => "¿Está seguro que desea borrar el usuario? Se borrarán todos los datos vinculados a él. Esta es una acción peligrosa.",
		'confirmar' => "Confirmar",
		'cancelar' => "Cancelar",
		'borrar' => "Borrar",
		'NOBorrar' => "No Borrar"
	 );
?>