<?php

	/* English language configuration */
	 $lang = array (
	 	'buscar' => "Search",
		'nombre' => "Name",
	  	'apellidos' => "Surname",
	  	'direccion' => "Address",
	  	'ciudad' => "City",
	  	'cp' => "ZIP Postal",
	  	'pais' => "Country",
	  	'email' => "Email",
	  	'telefono' => "Phone",
	  	'movil' => "Mobile phone",
	  	'nivel' => "Access Level",
	  	'creaccion' => "Creation Date",
	  	'caducidad' => "Expiration Date",
	  	'ultimo' => "Last Connection"
	 );
?>