<?php

	/* English language configuration */
	 $lang = array (
	  	'ultimo' => "Last Connection",
	  	'nada' => "Sorry, no items found",
	  	'mandar' => "Mail Send",
		'ficha' => "View User",	
		'activar' => "User Activate",
		'desactivar' => "User Deactivate",
		'contenidos' => "Contents",
		'nombre' => "Name and Surname",
		'mensaje' => "Send intern menssage",
		'acciones' => "Actions / State",
		'editar' => "User Edit"
	 );
?>