<?php

	/* Spanish language configuration */
	 $lang = array (
	 	'procesado' => "Se ha procesado la exportación",
		'OK' => "Procesada exportación correctamente",
		'KO' => "Ha habido problemas en la exportación",
		'descarga' => "Descarga el fichero resultado"
	 );
?>