<?php

	/* Spanish language configuration */
	 $lang = array (
	 	'fichero' => "El fichero a importar contiene los siguientes campos:",
		'numFilas' => "Número de filas",
		'numCampos' => "Número de campos",
		'nombre' => "Nombre",
		'apellidos' => "Apellidos",
		'direccion' => "Dirección",
		'ciudad' => "Ciudad",
		'municipio' => "Municipio",
		'CP' => "CP",
		'provincia' => "Provincia",
		'pais' => "País",
		'idioma' => "Idioma",
		'email' => "Email",
		'telefono' => "Teléfono",
		'movil' => "Móvil",
		'nombreEmpresa' => "Nombre de Empresa",
		'CIF' => "CIF",
		'nick' => "Nick",
		'enGrupo' => "Asignar al grupo",
		'anadirContactos' => "Importar contactos",
		'CSV' => "Vuelva a seleccionar el fichero CSV",
		'otrosCampos' => "Otros campos fijos",
		'activado' => "Activado",
		'si' => "Sí",
		'no' => "No",
		'boletin' => "Alta en boletín",
		'sms' => "Alta en SMS",
		'ExclusivoMailing' => "Usuario exclusivo para mailings",
		'nivelAcceso' => "Nivel de acceso",
		'numImportados' => "Número de usuarios importados",
		'numAsigGrupo' => "Número de usuarios asignados a grupo"
	 );
?>