<?php

	/* Spanish language configuration */
	 $lang = array (
	 	'noEncontrados' => "No encontrados contactos",
		'desactivar' => "Desactivar todos",
		'seleccionar' => "Seleccionar todos",
		'anadirContactos' => "Añadir Contactos a su Sistema",
		'yaExiste' => "Este usuario ya existe en nuestros sistemas",
		'enGrupo' => "Almacenar en algún grupo",
		'numImportados' => "Se han importado al sistema",
		'contactos' => "nuevos contactos"
	 );
?>