<?php

	/* Spanish language configuration */
	 $lang = array (
	 	'MSN' => "Añadir Contactos desde cuenta Hotmail / MSN",
		'Live' => "Añadir Contactos desde cuenta Windows Live",
		'Gmail' => "Añadir Contactos desde cuenta GMail",
		'Flickr' => "Añadir Contactos desde cuenta Flickr",
		'Hi5' => "Añadir Contactos desde cuenta Hi5",
		'LinkedIn' => "Añadir Contactos desde cuenta LinkedIn",
		'Terra' => "Añadir Contactos desde cuenta Terra",
		'Twitter' => "Añadir Contactos desde cuenta Twitter",
		'Xing' => "Añadir Contactos desde cuenta Xing",
		'Yahoo' => "Añadir Contactos desde cuenta Yahoo",
		'Youtube' => "Añadir Contactos desde cuenta Youtube",
		'usuario' => "Usuario",
		'contrasena' => "Contraseña",
		'extraer' => "Extraer Contactos"		
	 );
?>