<?php

	/* Spanish language configuration */
	 $lang = array (	 			
		'nombre' => "Nombre",
		'nivel' => "Nivel de Acceso",
	  	'enviar' => "enviar",
		'titulo_nuevo_grupo' => "Nuevo grupo",
		'titulo_editar_grupo' => "Editar grupo"
	 );
?>