<?php

	/* Spanish language configuration */
	 $lang = array (	 
		'errorPermisos' => "No tiene permisos para acceder a este área",
		'accesoIncorrecto' => "Error - Acceso incorrecto!",		 
		'crearUsuario' => "Crear usuario",
		'editarUsuario' => "Editar usuario",
		'personales' => "Datos Personales",
		'nick' => "Nick",
		'nombre' => "Nombre",
	  	'apellidos' => "Apellidos",
	  	'direccion' => "Dirección",
	  	'ciudad' => "Población",
		'municipio' => "Municipio",
	  	'cp' => "Código Postal",
		'provincia' => "Provincia",
	  	'pais' => "País",
		'idioma' => "Idioma en codificación internacional (por defecto Español ES-ES)",
	  	'email' => "Email",
	  	'telefono' => "Teléfono",
	  	'movil' => "Móvil",
		'configuracion' => "Datos de configuración",
		'password' => "Password",
	  	'nivel' => "Nivel de Acceso",	  	
	  	'caducidad' => "Fecha de Caducidad",
		'redirigirLogin' => "Redirigir tras el acceso usuario",
		'activado' => "Activado",
		'boletin' => "Alta Boletín",
		'SMS' => "Alta SMS",
		'exclusivo' => "Exclusivo Boletines",
		'empresariales' => "Datos de Caracter Empresarial",
		'empresa' => "Nombre Empresa",
		'nombreEmpresa' => "Nombre de la Empresa",
		'CIF' => "CIF",
		'foto' => "Foto del perfil",
		'imagenEditar' => "Sustituir/Añadir foto del perfil",
		'borrarImagen' => "Borrar foto del perfil",
	  	'enviar' => "guardar",
		'fechaNacimiento' => "Fecha de nacimiento",
		'estado' => "Estado",
		'gestiones' => "Gestiones",
		'tiene_tareas' => "Tiene tareas",
		'representante_presupuestos' => "Representante presupuestos",
		'familia_presupuestos' => "Familia presupuestos",
		'comunicaciones' => "Comunicaciones"
		);
?>