<?php

	/* Spanish language configuration */
	 $lang = array (
	 	'usuarios' => "Usuarios",
		'altas' => "Altas de usuarios",
	  	'anoAnterior' => "Año anterior",
		'anoSiguiente' => "Año siguiente",	  	
	  	'totalUsuarios' => "Total usuarios",
		'totalUsuariosBoletines' => "Total usuarios boletines",
	  	'accesosHoy' => "Accesos hoy",
		'accesosMes' => "Accesos mes actual",
		'accesosAno' => "Accesos año actual",
		'ene' => "Ene",
		'feb' => "Feb",
		'mar' => "Mar",
		'abr' => "Abr",
		'may' => "May",
		'jun' => "Jun",
		'jul' => "Jul",
		'ago' => "Ago",
		'sep' => "Sep",
		'oct' => "Oct",
		'nov' => "Nov",
		'dic' => "Dic"
	 );
?>