<?php

	/* Spanish language configuration */
	 $lang = array (
	 	'ficha' => "Ver Ficha",
		'mandar' => "Mandar Mail",
		'editar' => "Editar Usuario",
		'desvincular' => "Desvincular Usuario",
		'paginacionDel' => "Del",
		'paginacionAl' => "al",
		'paginacionTotal' => "de un total de",
		'acciones' => "Acciones",
		'activar' => "Activar usuario",
		'desactivar' => "Desactivar usuario",
		'desvincular' => "Desvincular usuario",
		'contenido' => "Contenido",
	  	'nombre' => "Nombre",
	  	'apellidos' => "Apellidos",
	  	'email' => "Email",
	  	'provincia' => "Provincia",
	  	'ciudad' => "Ciudad",
	  	'telefono' => "Teléfono",
	  	'movil' => "Móvil",
	  	'empresa' => "Nombre Empresa",
		'paginas' => "Páginas"
	 );
?>