<?php

	/* Spanish language configuration */
	 $lang = array (
		'errorPermisos' => "No tiene permisos para acceder a este área",
		'accesoIncorrecto' => "Error - Acceso incorrecto!",	
	 	'ficha' => "Ver ficha",
		'mandar' => "Mandar Mail",
	  	'errorNivel' => "Error: Intento de acceso a ficha de usuario con mayor Nivel",
		'nick' => "Nick",
	  	'nombre' => "Nombre",
	  	'apellidos' => "Apellidos",
	  	'direccion' => "Dirección",
		'ciudad' => "Ciudad",
		'municipio' => "Municipio",
		'provincia' => "Provincia",
		'cp' => "Código Postal",		
	  	'pais' => "País",
		'idioma' => "Idioma",
		'telefono' => "Teléfono",
		'movil' => "Móvil",
	  	'email' => "Email",
		'empresa' => "Datos de Empresa",
		'origen' => "Datos de Origen",
		'nombreEmpresa' => "Nombre de Empresa",
		'CIF' => "CIF",
		'otrosDatos' => "Otros datos",
		'referencia' => "Referido por",
		'referenciaWeb' => "Web origen",
		'redirigirLogin' => "Redirigir tras el acceso usuario",
		'vigencia' => "Vigencia / Accesos",	  	
	  	'creacion' => "Fecha de Creacción",
	  	'caducidad' => "Fecha de Caducidad",
	  	'ultimo' => "Fecha Último Acceso",
		'inicio' => "Inicio Suscripción",
		'fin' => "Fin Suscripción"
	 );
?>