<?php

	/* Spanish language configuration */
	 $lang = array (
		'nombre' => "Nombre",
		'apellidos' => "Apellidos",
		'ciudad' => "Ciudad",
		'municipio' => "Municipio",
		'provincia' => "Provincia",
		'pais' => "País",
		'empresa' => "Empresa",
		'buscar' => "Buscar",
		'heredados' => "Permisos heredados sobre",
		'vincular' => "Vincular a Grupo"
	 );
?>