<?php

	/* Spanish language configuration */
	 $lang = array (
	 	'errorPermisos' => "No tiene permisos para acceder a este área",
		'accesoIncorrecto' => "Error - Acceso incorrecto!",
		'datos' => "Datos",
		'nombre' => "Nombre",
		'padre' => "Padre",
		'sinonimos' => "Sinónimos (separados por comas)",
		'url' => "URL relacionada",
		'imagen' => "Imagen",
		'sinValor' => "Sin valor",
		'borrarImagen' => "Borrar imagen",
		'guardar' => "Guardar"
	 );
?>