<?php

	/* Spanish language configuration */
	 $lang = array (	 	
		'detalle' => "Detalle de contenidos",
		'ordenarClicks' => "Ver por orden de clicks",
		'ordenarVistas' => "Ver por orden de vistas",
		'vistas' => "Vistas",
		'clicks' => "Clicks"	
	 );
?>