<?php

	/* Spanish language configuration */
	 $lang = array (	 	
		'listado' => "Listado de Foros en el Sistema",
		'numero' => "Número de resultados",
		'mensajes' => "Mensajes",
		'editar' => "Editar Mensajes"
	 );
?>