<?php

	/* Spanish language configuration */
	 $lang = array (	 	
		'errorPermisos' => "No tiene permisos para acceder a este área",
		'accesoIncorrecto' => "Error - Acceso incorrecto!",
		'numeroResultados' => "Número de resultados",
		'termino' => "Término",
		'acciones' => "Acciones",
		'descripcion' => "Descripción",
		'editar' => "Editar",
		'borrar' => "Borrar",
		'enlace' => "Enlace"
	 );
?>