<?php

	/* Spanish language configuration */
	 $lang = array (	 
		'errorPermisos' => "No tiene permisos para acceder a este área",
		'accesoIncorrecto' => "Error - Acceso incorrecto!",
		'tags' => "Etiquetas de información",
		'borrar' => "Eliminar",
		'editar' => "Editar",
		'anadirHijo' => "Añadir hijo",
		'tipos' => "Tipos de Contenidos"
	 );
?>