<?php

	/* Spanish language configuration */
	 $lang = array (	 	
		'ultimos' => "Últimos mensajes añadidos",
		'contenido' => "Contenido",
		'votacion' => "Votación",
		'vistas' => "Vistas",
		'fecha' => "Fecha",
		'autor' => "Autor",
		'acciones' => "Acciones",
		'borrar' => "Borrar",
		'editar' => "Editar",
		'siguiente' => "siguiente",
		'anterior' => "anterior"
	 );
?>