<?php
	/* Spanish language configuration */
	 $lang = array (
		'busquedas' => "Búsquedas",
		'errorPermisos' => "No tiene permisos para acceder a este área",
		'accesoIncorrecto' => "Error - Acceso incorrecto!",
		'numeroResultados' => "Número de resultados",
		'fechaInicio' => "Fecha inicio",
		'fechaFin' => "Fecha fin",
		'busqueda' => "Búsqueda",
		'repeticiones' => "Repeticiones",
		'resultados' => "Resultados",
		'paginas' => "Páginas"
	 );
?>