<?php
	/* Spanish language configuration */
	 $lang = array (
		'maxClicks' => "Contenidos con mayor impacto global",
		'maxVistas' => "Contenidos con mayor visualización global",
		'maxVistasMes' => "Contenidos con mayor visualización en el mes actual",
		'maxClicksMes' => "Contenidos con mayor impacto en el mes actual",
		'raiz' => "Raiz"
	 );
?>