<?php
	/* Spanish language configuration */
	 $lang = array (
		'estaUsted' => "Está usted en la sección",
		'anoAnterior' => "Año Anterior",
		'anoSiguiente' => "Año Siguiente",
		'ene' => "Ene",
		'feb' => "Feb",
		'mar' => "Mar",
		'abr' => "Abr",
		'may' => "May",
		'jun' => "Jun",
		'jul' => "Jul",
		'ago' => "Ago",
		'sep' => "Sep",
		'oct' => "Oct",
		'nov' => "Nov",
		'dic' => "Dic",
		'estadisticasSeccion' => "Estadísticas de la sección"
	 );
?>