<?php
	/* Spanish language configuration */
	 $lang = array (
		'dominio' => "Dominio",
		'version' => "Versión",
		'subversion' => "Subversión",
		'usuarioBD' => "Usuario de acceso a Base de Datos",
		'passBD' => "Password de acceso a Base de Datos",
		'baseDatosBD' => "Nombre de la Base de Datos",
		'hostFTP' => "Nombre de host del FTP",
		'usuarioFTP' => "Usuario de acceso a FTP",
		'passFTP' => "Password de acceso a FTP",
		'estado' => "Estado de última actualización",
		'ok' => "Todo correcto",
		'ko' => "Con problemas",
		'guardar' => "Guardar"
	 );
?>