<?php

	/* Spanish language configuration */
	 $lang = array (	 	
		'arriba' => "Subir una posición",
		'toparriba' => "Subir a primera posición",
		'abajo' => "Bajar una posición",
		'topabajo' => "Bajar a última posición",
		'nuevo' => "Nuevo Elemento para este grupo de campos adicionales",
		'anadir' => "Añadir"
	 );
?>