<?php

	/* Spanish language configuration */
	 $lang = array (
		'dominio' => "Dominio",
		'version' => "Versión",
		'acciones' => "Acciones",
		'editarConfiguracion' => "Editar configuración de la web",
		'ver' => "Ir a la web",
		'admin' => "Administrar la web",
		'ok' => "Última actualización realizada correctamente",
		'ko' => "Incidencias en la última actualización",
		'actualizar' => "Actualizar"
	 );
?>