<?php

	/* Spanish language configuration */
	 $lang = array (	 	
		'logo' => "Logo",
		'dominio' => "Dominio",
		'version' => "Versión",
		'herramientas' => "Herramientas",
		'acciones' => "Acciones",
		'versiones' => "Control de versiones",
		'estado' => "Estado"
	 );
?>