<?php

	/* Spanish language configuration */
	 $lang = array (	 	
		'herramientas' => "Listado de herramientas",
		'herramientasPersonalizadas' => "Listado de herramientas personalizadas",
		'activada' => "Herramienta activada",
		'desactivada' => "Herramienta desactivada",
		'version' => "Versión",
		'enCentral' => "en la central",
		'enSistema' => "en este sistema",
		'acciones' => "Acciones",
		'estado' => "Estado"
	 );
?>