<?php

	/* Spanish language configuration */
	 $lang = array (	 	
		'instrucciones' => "Introduce el número de móvil en el que desea recibir las alertas. Si dejamos el campo vacio no se enviarán alertas",
		'movil' => "Número Móvil para recibir alerta",
		'enviar' => "enviar"
	 );
?>