<?php

	/* Spanish language configuration */
	 $lang = array (
		'buscarReservas' => "Buscar Reservas",
		'ID' => "Reserva con Id Reserva",
		'IDRestaurante' => "Reserva en Id Restaurante",
		'nombre' => "Reservas con Nombre",
		'telefono' => "Reservas con número de teléfono",
		'estado' => "Reservas por estado",					
		'confirmada' => "Reserva Confirmada",	
		'nodisponible' => "Reserva Sin Disponibilidad",
		'pendiente' => "Reserva Pendiente",
		'rechazada' => "Reserva Rechazada",
		'fraudulenta' => "Reserva Fraudulenta",
		'buscar' => "buscar"
	 );
?>