<?php

	/* Spanish language configuration */
	 $lang = array (	 	
		'restaurante' => "Restaurante",
		'nombre' => "Nombre del Usuario que hace la reserva",
		'telefono' => "Teléfono del Usuario que hace la reserva",
		'email' => "Email Usuario que hace la reserva",
		'dia' => "Día de la reserva",
		'formatoDia' => "Formato dd/mm/aaaa",
		'hora' => "Hora de la reserva",
		'formatoHora' => "Formato hh:mm",
		'comensales' => "Número de comensales",
		'alerta' => "Preferencia alerta",
		'SMS' => "SMS",
		'llamada' => "Llamada",
		'mail' => "Mail",
		'enviar' => "enviar"
	 );
?>