<?php

	/* Spanish language configuration */
	 $lang = array (
		'total' => "Total reservas recibidas",
		'recibidas' => "Reservas recibidas",
		'confirmada' => "Reservas Confirmadas",
		'totalConfirmadas' => "Total reservas confirmadas",
		'nodisponible' => "Reserva Sin Disponibilidad",
		'pendiente' => "Reservas Pendientes",
		'totalPendientes' => "Total reservas pendientes",
		'cancelada' => "Reservas canceladas",
		'totalCanceladas' => "Total reservas pendientes de saldar",
		'saldar' => "Reservas Pendientes Saldar",
		'totalSaldar' => "Reservas Pendientes Saldar",
		'anoSiguiente' => "Año Siguiente",
		'anoAnterior' => "Año Anterior",
		'ene' => "Ene",
		'feb' => "Feb",
		'mar' => "Mar",
		'abr' => "Abr",
		'may' => "May",
		'jun' => "Jun",
		'jul' => "Jul",
		'ago' => "Ago",
		'sep' => "Sep",
		'oct' => "Oct",
		'nov' => "Nov",
		'dic' => "Dic",
		'al' => "al",
		'estadisticas' => "Estadísticas de Negocio de Reservas",
	 );
?>