<?php

	/* Spanish language configuration */
	 $lang = array (	 	
		'confirmada' => "Reserva Confirmada",	
		'nodisponible' => "Reserva Sin Disponibilidad",
		'pendiente' => "Reserva Pendiente",
		'rechazada' => "Reserva Rechazada",
		'fraudulenta' => "Reserva Fraudulenta",
		'del' => "Del",
		'al' => "al",
		'informacion' => "Información",
		'acciones' => "Acciones",
		'verFicha' => "Ver Ficha Usuario",
		'verFichaNO' => "Ver Ficha Usuario no disponible",
		'estado' => "Estado",
		'paginas' => "Páginas",		
	 );
?>