<?php

	/* Spanish language configuration */
	 $lang = array (	 	
		'confirmada' => "Reserva Confirmada",	
		'nodisponible' => "Reserva Sin Disponibilidad",
		'pendiente' => "Reserva Pendiente",
		'rechazada' => "Reserva Rechazada",
		'fraudulenta' => "Reserva Fraudulenta",
		'EnTramite' => "Reserva en Trámite",
		'ficha' => "Ver ficha de usuario si está registrado",
		'cambiarEstado' => "Cambiar estado Reserva",
		'borrarReserva' => "Borrar Reserva",
		'leidoRestaurante' => "Leido por Restaurante",
		'leidoRestauranteNO' => "No leido por Restaurante",
		'gestionadoRestaurante' => "Gestionado por Restaurante",
		'gestionadoRestauranteNO' => "No gestionado por Restaurante",
		'comunicadoUsuario' => "Comunicado a Usuario",
		'comunicadoUsuarioNO' => "No comunicado a Usuario",
		'enviadoSeguimiento' => "Enviado Seguimiento Usuario",
		'leidoSeguimiento' => "Leido Seguimiento Usuario",
		'del' => "Del",
		'al' => "al",
		'deUnTotal' => "de un total de",
		'informacion' => "Información",
		'acciones' => "Acciones",
		'verFicha' => "Ver Ficha Usuario",
		'verFichaNO' => "Ver Ficha Usuario no disponible",
		'cambiarEstado' => "Cambiar Estado Reserva",
		'alertaSMS' => "Alerta SMS",
		'alertaMail' => "Alerta Mail",
		'alertaLlamada' => "Alerta Llamada",
		'comensales' => "Comensales",
		'estado' => "Estado",
		'paginas' => "Páginas",
		
		'administrar' => "Administrar"
	 );
?>