<?php

	/* Spanish language configuration */
	 $lang = array (	 	
		'telefono' => "Teléfono al que recibir las reservas",
		'tipo' => "Tipo de Restaurante con Alerta de Reserva",
		'todos' => "Todos los Restauranes",
		'online' => "Restaurantes con Reserva online",
		'ninguno' => "Ninguno",
		'enviar' => "enviar"
	 );
?>