<?php

	/* Spanish language configuration */
	 $lang = array (
		'concepto' => "Concepto",
		'baseImponible' => "Base Imponible",
		'impuesto' => "IVA",
		'trimestre' => "Trimestre",
		'total' => "Total",
		'fecha' => "Fecha",
		'numero' => "Número",
		'cif' => "CIF",
		'denominacionsocial' => "Denominación Social"
	 );
?>