<?php

	/* Spanish language configuration */
	 $lang = array (
	 	'buscar' => "Buscar",
		'acciones' => "Acciones",
		'cliente' => "Cliente",
		'editar' => "Editar cliente",
		'facturado' => "Total facturado",
		'facturado12' => "12 últimos meses",
		'contactos' => "Contactos",
		'nuevo_contacto' => "Nuevo contacto",
		'nuevoPresupuesto' => "Nuevo presupuesto",
		'sinValor' => "Sin asignar",
		'denominacionSocial' => "Denominación Social",
		'CIF' => "CIF",
		'municipio' => "Municipio",
	  	'cp' => "CP",
		'provincia' => "Provincia",
		'ciudad' => "Población",
		'web' => "Página web",
		'datosContacto' => "Datos de contacto",
		'nombre' => "Nombre",
	  	'apellidos' => "Apellidos",
		'telefono' => "Teléfono",
		'movil' => "Móvil",
		'datosFacturacion' => "Datos de facturación",
		'facturacion' => "Facturación global mayor de (€)",
		'facturacion12' => "Facturación últimos 12 meses mayor de (€)",
		'datosRepresentacion' => "Datos de representación / referenciación",
		'representante' => "Representante",
		'familia'=> "Familia",
		'numeroResultados' => "Número de resultados",
		'noResultados' => "No se han encontrado resultados en la Base de Datos",
		'facturas' => "Facturas relacionadas con cliente",
		'presupuestos' => "Presupuestos relacionados con el cliente",
		'nuevo_proyecto' => "Nuevo proyecto",
		'eliminar' => "Eliminar cliente"
	 );
?>