<?php

	/* Spanish language configuration */
	 $lang = array (
	 	'buscar' => "Buscar",
		'sinValor' => "Sin asignar",
		'denominacionSocial' => "Denominación Social",
		'CIF' => "CIF",
		'municipio' => "Municipio",
	  	'cp' => "CP",
		'provincia' => "Provincia",
		'ciudad' => "Población",
		'web' => "Página web",
		'datosContacto' => "Datos de contacto",
		'nombre' => "Nombre",
	  	'apellidos' => "Apellidos",
		'telefono' => "Teléfono",
		'movil' => "Móvil",
		'datosFacturacion' => "Datos de facturación",
		'facturacion' => "Facturación global mayor de (€)",
		'facturacion12' => "Facturación últimos 12 meses mayor de (€)",
		'datosRepresentacion' => "Datos de representación / referenciación",
		'representante' => "Representante",
		'familia'=> "Familia",
		'tipo' => "Tipo",
		'estado' => "Estado",
		'referencia' => "Referencia",
		'titulo_buscar_cliente' => "Buscar clientes"
	 );
?>