<?php

	/* Spanish language configuration */
	 $lang = array (
		'acciones' => "Acciones",
		'cliente' => "Cliente",
		'editar' => "Editar cliente/proveedor",
		'facturado' => "Total facturado",
		'facturado12' => "12 últimos meses",
		'contactos' => "Contactos",
		'nuevo_contacto' => "Nuevo contacto",
		'nuevoPresupuesto' => "Nuevo presupuesto",
		'representante' => "Representante",
		'numeroResultados' => "Número de resultados",
		'eliminar' => "Eliminar cliente/proveedor",		
		'facturas' => "Facturas relacionadas con cliente/proveedor",
		'presupuestos' => "Presupuestos relacionados con el cliente/proveedor",
		'titulo-clientes' => "Listado de clientes",
		'nuevo_proyecto' => "Nuevo proyecto",
		'acciones_comerciales' => "Acciones comerciales"
	 );
?>