<?php

	/* Spanish language configuration */
	 $lang = array (
		'acciones' => "Acciones",
		'numeroResultados' => "Número de resultados",
		'editar' => "Editar apunte",		
		'facturaRelacionada' => "Factura relacionada",
		'fecha' => "Fecha",		
		'cliente' => "Cliente",
		'titulo' => "Titulo",
		'importe' => "Importe",
		'cliente' => "Empresa",
		'saldoTotalizado' => "Saldo totalizado"
	 );
?>