<?php

	/* Spanish language configuration */
	 $lang = array (
		'acciones' => "Acciones",
		'reasignar' => "Reasignar contacto a otro cliente",
		'editar' => "Editar contacto",
		'nombre' => "Nombre",
		'apellidos' => "Apellidos",
		'movil' => "Móvil",
		'email' => "Email",
		'mandarMail' => "Mandar Email",
		'cargo' => "Cargo",
		'noResultados' => "No se han encontrado resultados en la base de datos",
		'representante' => "Representante"
	 );
?>