<?php

	/* Spanish language configuration */
	 $lang = array (
		'acciones_crm' => "Acciones CRM",
		'animo_vender' => "Ánimo, toca vender",		
		'planificar_relacion_cliente' => "Planificar relación/contacto con cliente u oportunidad",
		'en_plazo' => "En plazo",
		'fuera_plazo' => "Fuera de plazo",
		'ver_editar_presupuesto' => "Ver/editar presupuesto",
		'ver_editar_cliente' => "Ver/editar cliente",
		'registrar_resultado' => "Registrar resultado",
		'pendientes' => "Pendientes",
		'planificar_crm' => "Planificar relación/contacto con cliente u oportunidad",
		'ejecutadas' => "Ejecutadas"
	 );
?>