<?php

	/* Spanish language configuration */
	$lang = array (
		'errorPermisos' => "No tiene permisos para acceder a este área",
		'accesoIncorrecto' => "Error - Acceso incorrecto!",
		'seguro' => "Está realizando una accion peligrosa. ¿Está seguro que desea eliminar el cliente y todos sus datos asociados?",
		'noPosibleFacturas' => "No es posible realizar el borrado. Este cliente tiene facturas vinculadas",
		'volver' => "Volver",
		'confirmar' => "Confirmar",
		'cancelar' => "Cancelar"		
	);
?>