<?php

	/* Spanish language configuration */
	$lang = array (
		'errorPermisos' => "No tiene permisos para acceder a este área",
		'accesoIncorrecto' => "Error - Acceso incorrecto!",
		'acciones' => "Acciones",
		'tareas_asignadas' => "Tareas asignadas",
		'tareas_responsable' => "Tareas responsable",
		'nombre' => "Nombre",	
		'horas_semana' => "Horas fichadas 7 días",
		'horas_hoy' => "Horas fichadas hoy",
		'fecha' => "Fecha",
		'fechaFin' => "Fecha fin"
	);
?>