<?php

	/* Spanish language configuration */
	 $lang = array (
		'errorPermisos' => "No tiene permisos para acceder a este área",
		'accesoIncorrecto' => "Error - Acceso incorrecto!",
	 	'buscar' => "Buscar",
		'sinValor' => "Sin asignar",
		'familia'=> "Familia",
		'fecha1' => "Fecha desde",
		'fecha2' => "Fecha hasta",
		'representante' => "Representante",
		'titulo_facturas_buscar' => "Buscar facturas"
	 );
?>