<?php

	/* Spanish language configuration */
	 $lang = array (
		'acciones' => "Acciones",
		'numeroResultados' => "Número de resultados",
		'generarSiguiente' => "Generar siguiente factura",
		'periodicidad' => "Periodicidad",		
		'cliente' => "Cliente",
		'titulo' => "Titulo",
		'baseImponible' => "Base imponible",
		'acumulado' => "Acumulado",
		'ultima' => "Última",
		'facturas' => "Facturas",
		'subtotal' => "Subtotal",
		'subtotalAnual' => "Subtotal anual",
		'total' => "Total anual",
		'facturasIngreso'=> "Facturas de ingreso",
		'facturasGasto' => "Facturas de gasto"
	 );
?>