<?php

	/* Spanish language configuration */
	 $lang = array (
		'acciones' => "Acciones",
		'numeroResultados' => "Número de resultados",
		'vencimiento' => "Vencimiento",		
		'cliente' => "Cliente",
		'estado' => "Estado",
		'baseImponible' => "Base imponible",
		'titulo' => "Titulo",
		'numeroFactura' => "Número factura",
		'editar' => "Editar factura",
		'insertarPago' => "Insertar pago",
		'presupuestoRelacionado' => "Presupuesto relacionado",
		'total' => "Total facturado y previsto facturar",
		'saldado' => "Saldado",
		'generarFacturaImprimible' => "Generar factura imprimible",
		'descargar' => "Descargar factura",
		'noFacturas' => "No hay facturas vinculadas a este presupuesto",
		'facturar' => "Emitir nueva factura vinculada al presupuesto",
		'rectificativa' => "Rectificativa",
		'noSaldado' => "No saldado"
	 );
?>