<?php

	/* Spanish language configuration */
	 $lang = array (
		'sinValor' => "Sin asignar",
		'fecha' => "Fecha de la factura (formato aaaa-mm-dd)",
		'vencimiento' => "Fecha vencimiento (formato aaaa-mm-dd)",		
		'cliente' => "Cliente",
		'nombreEmpresa' => "Denominación Social (no clientes)",
		'estado' => "Estado",
		'impuestos' => "Impuestos",
		'BaseImponible' => "Base Imponible",
		'textoLinea' => "Texto línea",
		'anadirLinea' => "Añadir línea",
		'porcentaje' => "Porcentaje",
		'eliminar' => "Eliminar línea",
		'empresa' => "Facturar con empresa",
		'periodicidad' => "Periodicidad",
		'numeroFactura' => "Número Factura",
		'titulo' => "Título",
		'guardar' => "Guardar",
		'serieFactura' => "Serie factura",
		'formaPago' => "Forma de pago",
		'transferencia' => "Transferencia bancaria",
		'reciboDomiciliado' => "Recibo domiciliado",
		'titulo_facturar_presupuesto' => "Facturar presupuesto"
	 );
?>