<?php

	/* Spanish language configuration */
	 $lang = array (
		'numeroFactura' => "Número de factura",
		'fecha' => "Fecha de la factura",
		'vencimiento' => "Fecha vencimiento",	
		'concepto' => "Concepto",
		'baseImponible' => "Base Imponible",
		'impuesto' => "Impuesto",
		'subtotal' => "Subtotal",
		'total' => "Total",		
		'cliente' => "Datos cliente",
		'formaPago' => "Forma de pago",
		'transferencia' => "transferencia bancaria",
		'reciboDomiciliado' => "recibo domiciliado",
		'cuentaBancaria' => "IBAN:"
	);
?>