<?php

	/* Spanish language configuration */
	 $lang = array (
		'errorPermisos' => "No tiene permisos para acceder a este área",
		'accesoIncorrecto' => "Error - Acceso incorrecto!",
		'acciones' => "Acciones",
		'numeroResultados' => "Número de resultados",
		'vencimiento' => "Vencimiento",		
		'cliente' => "Cliente",
		'estado' => "Estado",
		'baseImponible' => "Base imponible",
		'titulo' => "Titulo",
		'numeroFactura' => "Número factura",
		'editar' => "Editar factura",
		'insertarPago' => "Insertar pago",
		'presupuestoRelacionado' => "Presupuesto relacionado",
		'saldado' => "Saldado",
		'generarFacturaImprimible' => "Generar factura imprimible",
		'descargar' => "Descargar factura",
		'facturado' => "Facturado",	
		'mes' => "Mes",
		'tituloGrafico1' => "Facturación por meses",
		'tituloGrafico3' => "Facturación actual y prevista",
		'facturacion' => "Facturación",
		'facturadoMesActual' => "Facturado mes actual",
		'facturadoAnoActual' => "Facturado año actual",
		'facturadoAnoAnterior' => "Facturado año anterior",
		'facturadoPrevisto' => "Facturado previsto",
		'riesgo' => "Riesgo",
		'valor' => "Valor",
		'rectificativa' => "Rectificativa",		
		'noSaldado' => "No saldado",
		'pendientesPago' => "Pendientes de pago",
		'totalizado' => "Totalizado",
		'busqueda' => "Búsqueda",
		'enviarPorMail' => "Enviar factura por mail a cliente",
		'enviada' => "Enviada",
		'descargada' => "Descargada",
		'IVAinc' => "IVA inc",
		'gastos' => "Gastos",
		'facturasGasto' => "Facturas de gasto",
		'siguienteFactura' => "Generar siguiente factura",
		'facturasIngreso' => "Facturas de ingreso",
		'titulo-facturas' => "Listado de facturas",
		'fecha' => "Fecha",
		'todas' => "Todas",
		'ninguna' => "Ninguna",
		'facturar_presupuesto' => "Emitir nueva factura vinculada al presupuesto",
		'editar_presupuesto_origen' => "Editar presupuesto origen",
		'necesario3meses' => "Necesario a 3 meses",
		'facturacionMediaMensual' => "Facturación media mensual",
		'gastosMediaMensual' => "Gastos medios mensuales",
		'balance' => "Balance",
		'gastos_previstos' => "Gastos previstos",
		'ingresos_previstos' => "Ingresos previstos",
		'buscar' => "Buscar factura"
	 );
?>