<?php

	/* Spanish language configuration */
	 $lang = array (
		'nombre' => "Nombre",	
		'fecha' => "Fecha",		
		'creador' => "Creador",
		'asignado' => "Asignado",
		'horas' => "Horas",
		'tipo' => "Tipo",
		'paginas' => "Páginas"
	 );
?>