<?php

	/* Spanish language configuration */
	 $lang = array (
		'errorPermisos' => "No tiene permisos para acceder a este área",
		'accesoIncorrecto' => "Error - Acceso incorrecto!",	
		'nuevaTarea' => "Nueva tarea",
		'sinValor' => "Sin asignar",
		'tareaEditada' => "Tarea editada que tienes asignada",
		'tareaEditadaResponsable' => "Tarea editada de la que eres responsable",
		'tareaTerminada' => "Tarea terminada",
		'tiempo_dedicado' => "Tiempo dedicado (h)",
		'nombre' => "Nombre",	
		'porcentaje' => "Porcentaje ejecución",	
		'descripcion' => "Descripción",
		'AsignadoA' => "Asignado A",
		'responsable' => "Responsable",
		'proyecto' => "Proyecto",
		'tipo' => "Tipo",
		'publico' => "Público",
		'si' => "Sí",
		'no' => "No",
		'guardar' => "Guardar",
		'fechaComienzo' => "Fecha comienzo (aaaa-mm-dd)",
		'fechaFin' => "Fecha fin (aaaa-mm-dd)",		
		'notificacionCreacion' => "Notificación en la creación",
		'notificacionModificacion' => "Notificación en la modificación",
		'notificacionCierre' => "Notificación en el cierre",
		'notificacionPasadoFecha' => "Notificación por retraso en fecha",
		'asignado' => "Asignado",
		'cliente' => "Cliente",
		'reabrirTarea' => "Reabrir tarea",
		'titulo_nueva_tarea' => "Nueva tarea",
		'eliminar_tarea' => "Eliminar tarea",
		'confirmada' => "Confirmada",
		'marcar_confirmada' => "Marcar como confirmada"
	 );
?>