<?php

	/* Spanish language configuration */
	 $lang = array (
		'errorPermisos' => "No tiene permisos para acceder a este área",
		'accesoIncorrecto' => "Error - Acceso incorrecto!",
		'sinValor' => "Sin asignar",
		'fecha' => "Fecha de la factura (formato aaaa-mm-dd)",
		'vencimiento' => "Fecha vencimiento (formato aaaa-mm-dd)",		
		'cliente' => "Cliente",
		'proveedor' => "Proveedor",
		'nombreEmpresa' => "Denominación Social (no clientes)",
		'estado' => "Estado",
		'impuestos' => "Impuestos",
		'BaseImponible' => "Base Imponible",
		'textoLinea' => "Texto línea",
		'anadirLinea' => "Añadir línea",
		'empresa' => "Facturar con empresa",
		'periodicidad' => "Periodicidad",
		'numeroFactura' => "Número Factura",
		'saldada' => "Saldada",
		'si' => "si",
		'no' => "no",
		'titulo' => "Título",
		'rectificativa' => "Rectificativa",
		'relacionada' => "Id Factura relacionada",
		'ultimaFactura' => "Última factura registrada por fecha",
		'serie' => "Serie de facturas periódicas",
		'guardar' => "Guardar",
		'serieFactura' => "Serie factura",
		'saldadaComision' => "Saldada comisión comercial",
		'fechaSaldada' => "Fecha pago",
		'pagoFactura' => "Saldada factura",
		'formaPago' => "Forma de pago",
		'transferencia' => "Transferencia bancaria",
		'reciboDomiciliado' => "Recibo domiciliado",
		'facturaGasto' => "Factura de gasto",
		'facturaIngreso' => "Factura de ingreso",
		'tipoFacturaGasto' => "Es un gasto o un ingreso?",
		'titulo_nueva_factura' => "Nueva factura",
		'titulo_editar_factura' => "Editar factura"
	 );
?>