<?php

	/* Spanish language configuration */
	 $lang = array (
		'errorPermisos' => "No tiene permisos para acceder a este área",
		'accesoIncorrecto' => "Error - Acceso incorrecto!",	
		'tituloNuevaAccionCRM' => "Nueva acción CRM",
		'tituloEditarAccionCRM' => "Editar acción CRM",
		'sinValor' => "Sin asignar",
		'cliente' => "Cliente",
		'titulo' => "Título",
		'asignado' => "Asignado",
		'descripcion' => "Detalles de la acción",	
		'fechaPlanificada' => "Fecha planificada",	
		'fechaRealizada' => "Fecha realizada",	
		'descripcion' => "Descripción",
		'AsignadoA' => "Asignado A",
		'tipo' => "Tipo",
		'reunion' => "Reunión",
		'cafe' => "Café",
		'llamada' => "Llamada",		
		'guardar' => "Guardar",
		'sincronizar' => "Sincronizar calendario",
		'hora' => "Hora",
		'fecha' => "Fecha",
		'minuto' => "Minuto",
		'invitar' => "Enviar invitación"
	 );
?>