<?php

	/* Spanish language configuration */
	 $lang = array (
		'errorPermisos' => "No tiene permisos para acceder a este área",
		'accesoIncorrecto' => "Error - Acceso incorrecto!",	
		'titulo' => "Título",
		'importe' => "Importe",
		'fecha' => "Fecha (aaaa-mm-dd)",
		'cliente' => "Cliente",
		'sinValor' => "Sin asignar",
		'empresa' => "Empresa",
		'facturaRelacionada' => "Id factura relacionada",
		'porcentajeReparto' => "Porcentaje reparto",
		'saldadoReparto' => "Saldado reparto",
		'si' => "Sí",
		'no' => "No",
		'guardar' => "Guardar"
	 );
?>