<?php

	/* Spanish language configuration */
	 $lang = array (
	 	'errorPermisos' => "No tiene permisos para acceder a este área",
		'accesoIncorrecto' => "Error - Acceso incorrecto!",	
		'sinValor' => "Sin asignar",
		'representante' => "Representante",
		'familia' => "Familia",		
		'nombreEmpresa' => "Denominación social",
		'nombreComercial' => "Nombre Comercial",
		'CIF' => "CIF",
		'poblacion' => "Población",
		'municipio' => "Municipio",
		'provincia' => "Provincia",
		'CP' => "Código Postal",
		'direccion' => "Dirección social",
		'telefono' => "Teléfono",
		'email' => "Emails (; para separar varios)",
		'datosBancarios' => "Datos bancarios",
		'numeroCuenta' => "Número de cuenta",
		'cuentaBanco' => "Banco",
		'cuentaSucursal' => "Sucursal",
		'cuentaDigitoControl' => "Dígito de control",
		'datosContactos' => "Datos de contactos",
		'cargo' => "Cargo",
		'nombreContacto' => "Nombre",
		'apellidosContacto' => "Apellidos",
		'emailContacto' => "Email",
		'movilContacto' => "Movil",
		'notas' => "Notas",
		'web' => "Página web",
		'guardar' => "Guardar",
		'login' => "Usuario (Email)",
		'pass' => "Contraseña",		
		'datosLogin' => "Datos de acceso",
		'estado' => "Estado",
		'tipo' => "Tipo",
		'errorTelefono' => "Error con el teléfono. Existe otro cliente con el mismo teléfono. Problema de duplicidad.",
		'errorReferencia' => "Error con la referencia. Existe otro cliente con la misma referencia. Problema de duplicidad.",
		'volver' => "Volver",
		'referencia' => "Referencia",
		'IBAN' => "IBAN",
		'idusuario' => "Id Usuario",
		'clienteOProveedor' => "Es un cliente o un proveedor?",
		'cliente' => "Cliente",
		'proveedor' => "Proveedor",
		'titulo_nuevo_cliente' => "Nuevo cliente",
		'titulo_editar_cliente' => "Editar cliente"
	 );
?>