<?php

	/* Spanish language configuration */
	 $lang = array (
		'errorPermisos' => "No tiene permisos para acceder a este área",
		'accesoIncorrecto' => "Error - Acceso incorrecto!",	
		'sinValor' => "Sin asignar",
		'representante' => "Representante",
		'datosContactos' => "Datos de contactos",
		'cargo' => "Cargo",
		'nombreContacto' => "Nombre",
		'apellidosContacto' => "Apellidos",
		'emailContacto' => "Email",
		'movilContacto' => "Movil",
		'guardar' => "Guardar"
	 );
?>