<?php

	/* Spanish language configuration */
	 $lang = array (
		'nombre' => "Nombre",	
		'descripcion' => "Descripción",
		'sinValor' => "Sin asignar",
		'responsable' => "Responsable",
		'cliente' => "Cliente",
		'plantilla' => "Plantilla",
		'guardar' => "Guardar",
		'mantenimiento' => "Proyecto mantenimiento",
		'titulo_nuevo_proyecto' => "Nuevo proyecto",
		'titulo_editar_proyecto' => "Editar proyecto",
		'equipo_involucrado' => "Equipo involucrado"
	 );
?>