<?php

	/* Spanish language configuration */
	 $lang = array (
		'errorPermisos' => "No tiene permisos para acceder a este área",
		'accesoIncorrecto' => "Error - Acceso incorrecto!",
		'sinValor' => "Sin asignar",
		'cliente' => "Cliente",
		'nombreEmpresa' => "Denominación Social (no clientes)",
		'nombreContacto' => "Nombre del contacto en la empresa",
		'email' => "Email",
		'telefono' => "Teléfono",
		'tituloSolicitud' => "Título de solicitud de presupuesto",
		'solicitud' => "Descripción de solicitud de presupuesto",
		'fechaCreacion' => "Fecha de creación del presupuesto (formato aaaa-mm-dd)",
		'fechaEnvio' => "Fecha de envío (formato aaaa-mm-dd)",
		'tituloEnvio' => "Título de presupuesto enviado",
		'descripcionEnvio' => "Descripción de presupuesto enviado",
		'estado' => "Estado del presupuesto",
		'representante' => "Representante",
		'familia' => "Familia",
		'impuestos' => "Impuestos",
		'BaseImponible' => "Base Imponible",
		'textoLinea' => "Texto línea",
		'notas' => "Notas",
		'anadirLinea' => "Añadir línea",
		'guardar' => "Guardar",
		'titulo_nuevo_presupuesto' => "Nuevo presupuesto",
		'titulo_editar_presupuesto' => "Editar presupuesto"
	 );
?>