<?php
	/* Spanish language configuration */
	 $lang = array (
		'acciones' => "Acciones",
		'cliente' => "Cliente",
		'fecha' => "Fecha",
		'envio' => "Envío",
		'total' => "Total",
		'estado' => "Estado",
		'presupuestos' => "Presupuestos",
		'tituloGrafico1' => "Estado presupuestos a 3 meses",
		'tituloGrafico2' => "Estado presupuestos a 1 año",
		'editar' => "Editar presupuesto",
		'facturar' => "Facturar presupuesto o parte de él",
		'representante' => "Representante",
		'numeroResultados' => "Número de resultados",
		'titulo-presupuestos' => "Listado de presupuestos",
		'facturas' => "Facturas relacionadas con presupuesto",
		'planificar_seguimiento_comercial' => "Planificar seguimiento comercial"
	 );
?>