<?php
	/* Spanish language configuration */
	 $lang = array (
		'tareas' => "Tareas del proyecto",
		'nuevaTarea' => "Crear tarea del proyecto",
		'numeroResultados' => "Número de resultados",
		'acciones' => "Acciones",
		'cliente' => "Cliente",
		'tareasAbiertas' => "Tareas abiertas",
		'tareasCerradas' => "Tareas cerradas",
		'porcentaje' => "Porcentaje ejecución",
		'nombre' => "Nombre",
		'proyectosActivos' => "Proyectos activos",
		'proyectosNoActivos' => "Proyectos cerrados",
		'proyectosTodos' => "Todos los proyectos",
		'proyectosPlantillas' => "Plantillas",
		'proyectosMantenimientos' => "Mantenimientos",
		'titulo-proyectos' => "Listado de proyectos",
		'buscar' => "Buscar proyecto",
		'hecho' => "Finalizar proyecto"
	 );
?>