<?php

	/* Spanish language configuration */
	 $lang = array (
	 	'buscar' => "Buscar",
		'buscarCliente' => "Buscar cliente al que reasignar el contacto",
		'seleccionaCliente' => "Selecciona cliente al que reasignar el contacto",
		'sinValor' => "Sin asignar",
		'denominacionSocial' => "Denominación Social",
		'CIF' => "CIF",
		'municipio' => "Municipio",
	  	'cp' => "CP",
		'provincia' => "Provincia",
		'ciudad' => "Población",
		'web' => "Página web",
		'noResultados' => "No se han encontrado resultados en la Base de Datos"
	 );
?>