<?php

	/* Spanish language configuration */
	$lang = array (
		'errorPermisos' => "No tiene permisos para acceder a este área",
		'accesoIncorrecto' => "Error - Acceso incorrecto!",
		'acciones' => "Acciones",
		'tareasDeProyecto' => "Tareas del proyecto",
		'tareasAbiertas' => "Tareas abiertas",
		'tareasCerradas' => "Tareas cerradas",
		'tareasTodas' => "Todas las tareas",
		'desde' => "Desde",
		'hasta' => "Hasta",
		'nombre' => "Nombre",	
		'fecha' => "Fecha",
		'fechaFin' => "Fecha fin",
		'creador' => "Creador",
		'asignado' => "Asignado",
		'ejecucion' => "% Ejecución",
		'horas' => "Horas",
		'tipo' => "Tipo",
		'entrar' => "Empezar computación de tiempo",
		'parar' => "Parar computación de tiempo",
		'editar' => "Editar tarea",		
		'hecho' => "Marcar como hecho",
		'numeroResultados' => "Número de resultados",
		'paginas' => "Páginas",
		'noAplica' => "N/A",
		'buscar' => "Buscar tarea"
	);
?>