<?php

	/* Spanish language configuration */
	 $lang = array (
	 	'titulo' => "Zona Privada",
		'nivel' => "Nivel de Acceso",
	  	'caducidad' => "Fecha de Caducidad",
	  	'grupos' => "Pertenencia a los grupos",
	  	'suscrito' => "Suscrito a las siguientes secciones",
		'tareas_responsable' => "Responsable",
		'tareas_asignadas' => "Asignadas",
		'crear_tarea' => "Crear tarea",
		'acciones' => "Acciones",
		'nombre' => "Nombre",	
		'fecha' => "Fecha",
		'fechaFin' => "Fecha fin",
		'creador' => "Creador",
		'asignado' => "Asignado",
		'ejecucion' => "% Ejecución",
		'horas' => "Horas",
		'proyecto' => "Proyecto",
		'tareas_involucracion' =>"Tareas pendientes en las que estás involucrado",
		'entrar' => "Empezar computación de tiempo",
		'parar' => "Parar computación de tiempo",
		'editar' => "Editar tarea",		
		'hecho' => "Marcar como hecho",
		'para_hacer' => "Para hacer",
		'nueva_para_hacer' => "Nueva microtarea a hacer",
		'acciones_crm' => "Acciones CRM",
		'animo_vender' => "Ánimo, toca vender",		
		'planificar_relacion_cliente' => "Planificar relación/contacto con cliente u oportunidad",
		'en_plazo' => "En plazo",
		'fuera_plazo' => "Fuera de plazo",
		'ver_editar_presupuesto' => "Ver/editar presupuesto",
		'ver_editar_cliente' => "Ver/editar cliente",
		'registrar_resultado' => "Registrar resultado",
		'fichar' => "Fichar",
		'fichar_entrar' => "Fichar para entrar",
		'mensaje_fichar_entrar' => "Fichado correctamente para entrar.",
		'mensaje_fichar_salir' => "Fichado correctamente para salir.",
		'problemas_fichar' => "Problemas en el sistema de fichado.",
		'fichar_salir' => "Fichar para salir"
	 );
?>