<?php

	/* Spanish language configuration */
	 $lang = array (
	 	'titulo' => "Back Office",
		'nivel' => "Access Level",
	  	'caducidad' => "Expiration Date",
	  	'grupos' => "Member of",
	  	'suscrito' => "Subscribe to this sections"
	 );
?>