<?php

	/* Spanish language configuration */
	 $lang = array (
		'noContenidos' => "No hay contenidos seleccionados",		
		'vistas' => "vistas",
		'clicks' => "clicks",
		'Nombre' => "Nombre",
		'Provincia' => "Provincia",
		'Pais' => "País",
		'Email' => "Email",
		'Visualizaciones' => "Visualizaciones",
		'Clicks' => "Clicks",
		'Enviado' => "Enviado",
		'EnviadoPendiente' => "Enviado pendiente de confirmar lectura",
		'Pendiente' => "Pendiente de envío",
		'Fallido' => "Fallido",
		'numeroResultados' => "Número de resultados",		
		'noUsuarios' => "No hay usuarios seleccionados"
	 );
?>