<?php

	/* Spanish language configuration */
	 $lang = array (
		'enviar' => "Enviar Boletín",
		'editar' => "Editar Boletín",
		'configuracion' => "Configurar Boletín",
		'borrar' => "Borrar Boletín",
		'parcialmente' => "parcialmente enviado",
		'pendiente' => "pendiente enviar",
		'totalmente' => "totalmente enviado",
		'asunto' => "Asunto Mail",
		'fecha' => "Fecha Envío",
		'estado' => "Estado",
		'pendientesEnvio' => "Pendientes Envío",
		'numeroResultados' => "Número de resultados",
		'misBoletines' => "Mis boletines",
		'todosBoletines' => "Todos los boletines",
		'acciones' => "Acciones"
	 );
?>