<?php

	/* Spanish language configuration */
	 $lang = array (	 	
		'zona' => "Zona",
		'borrar' => "Desvincular contenido del Boletín",
		'desplegado' => "Contenido mostrado desplegado",
		'resumen' => "Contenido mostrado en resumen y pulsar para ver el resto",
		'visualizacion' => "Cambiar visualización",
		'borrarUsuario' => "Desvincular usuario del Boletín",
		'arriba' => "Subir una posición",
		'toparriba' => "Subir a primera posición",
		'abajo' => "Bajar una posición",
		'topabajo' => "Bajar a última posición",
		'NOcontenidos' => "No hay contenidos seleccionados",
		'NOusuarios' => "No hay usuarios seleccionados",
		'Nombre' => "Nombre",		
		'Empresa' => "Empresa",
		'Provincia' => "Provincia",
		'Pais' => "País",
		'numeroResultados' => "Número de resultados",		
		'Email' => "Email"
	 );
?>