<?php

	/* Spanish language configuration */
	 $lang = array (
		'noExiste' => "No existe este SMS en bloque!",
		'noPropietario' => "No es usted propietario de este SMS en bloque!",
		'titulo' => "Título interno",
		'texto' => "Texto del SMS",
		'remitente' => "Número del Remitente",		
		'WAP' => "Enlace WAP Push",
		'pruebas' => "Número Móvil de Pruebas",
		'guardar' => "guardar"		
	 );
?>