<?php

	/* Spanish language configuration */
	 $lang = array (
		'noExiste' => "No existe este boletín!",
		'noPropietario' => "No es usted propietario de este boletín!",
		'cabecera' => "Plantilla Cabecera",
		'cuerpo' => "Plantilla Cuerpo",
		'pie' => "Plantilla Pie",
		'titulo' => "Título",		
		'remitente' => "Email Remitente",
		'emailRemitente' => "Nombre Remitente",
		'pruebas' => "Mail de Pruebas",
		'zonas' => "Zonas de contenido en el boletín",		
		'guardar' => "guardar"		
	 );
?>
