<?php

	/* Spanish language configuration */
	 $lang = array (		
		'texto' => "Texto del SMS",
		'remitente' => "Número del Remitente",
		'destinatario' => "Número del Destinatario",
		'WAP' => "Enlace WAP Push",
		'pruebas' => "Número Móvil de Pruebas",
		'enviar' => "enviar"		
	 );
?>