<?php

	/* Spanish language configuration */
	 $lang = array (
		'sinPermisos' => "No tiene permisos para enviar este boletín",
		'vasEnviar' => "Vas a enviar un boletín. Si estás seguro selecciona el número de envíos a realizar. Recuerda que boletines grandes tendrán que enviarse en varios tramos.",
		'numEnvios' => "Número de envíos en esta tanta",
		'enviar' => "Enviar"
	 );
?>