<?php

	/* Spanish language configuration */
	 $lang = array (
		'estadisticas' => "Ver Estadísticas del Boletín Enviado",
		'espere' => "Por favor, espere ... Barra de progreso de envío",
		'enviadoYa' => "Se han enviado ya",
		'deTotal' => " de un total de",
		'mensajes' => "mensajes",
		'correcto' => "Envío realizado correctamente",
		'enviados' => "mensajes enviados",
		'boletines' => "Ver Boletines"
	 );
?>