<?php

	/* Spanish language configuration */
	 $lang = array (
		'noCreditos' => "Error: No tiene suficientes créditos para realizar este envío!",
		'numeroMandados' => "NÚMERO DE SMS MANDADOS",
		'creditosDisponibles' => "NÚMERO DE CRÉDITOS DISPONIBLES TRAS ENVÍO",
		'volver' => "Volver al listado de SMS Marketing"
	 );
?>