<?php

	/* Spanish language configuration */
	 $lang = array (
		'estadisticas' => "Estadísticas de boletines",
		'nombre' => "Nombre",
		'fechaEnvio' => "Fecha de envío",
		'verEstadisticas' => "Ver estadísticas de boletín",
		'enviados' => "Enviados",
		'vistas' => "Vistas",
		'clicks' => "Clicks",
		'enviadosTotal' => "Enviados total",
		'vistasTotal' => "Vistas total",
		'clicksTotal' => "Clicks total"
	 );
?>