<?php

	/* Spanish language configuration */
	 $lang = array (	 	
		'sinAbrir' => "Mensaje sin abrir",
		'abierto' => "Mensaje abierto",
		'responder' => "Responder mensaje",
		'borrar' => "Borrar mensaje",
		'marcar' => "Marcar como favorito",
		'desMarcar' => "Desmarcar como favorito",
		'quitadoFavoritos' => "Mensaje quitado de favoritos",
		'anadidoFavoritos' => "Mensaje añadido a favoritos",
		'borrado' => "Mensaje borrado correctamente",
		'noBorrado' => "Mensaje no borrado correctamente. No tiene permisos para borrarlo",
		'listado' => "Listado de mensajes recibidos",
		'listadoFavoritos' => "Listado de mensajes marcados como favoritos",
		'acciones' => "Acciones / Estado",
		'asunto' => "Asunto",
		'de' => "Mensaje De",
		'fechaEnvio' => "Fecha de Envío",
		'sinMensajes' => "No tiene mensajes en la bandeja de entrada",
		'sinMensajesFavoritos' => "No tiene mensajes marcados como favoritos",
		'comunicadoMail' => "Comunicado por mail",
		'noComunicadoMail' => "No comunicado por mail",
		'abiertoMensaje' => "Abierto mensaje",
		'noAbiertoMensaje' => "Abierto mensaje",
		'estado' => "Estado",
		'cuerpo' => "Cuerpo del mensaje"
	 );
?>