<?php

	/* Spanish language configuration */
	 $lang = array (
		'titulo' => "Título interno",
		'texto' => "Texto del SMS",
		'remitente' => "Número del Remitente",
		'WAP' => "Enlace WAP Push",
		'pruebas' => "Número Móvil de Pruebas",
		'guardar' => "guardar"		
	 );
?>