<?php

	/* Spanish language configuration */
	 $lang = array (
	 	'buscar' => "Buscar",
		'nombre' => "Nombre",
	  	'apellidos' => "Apellidos",
	  	'direccion' => "Dirección",
	  	'ciudad' => "Población",
		'municipio' => "Municipio",
	  	'cp' => "CP",
		'provincia' => "Provincia",
	  	'pais' => "País",
	  	'email' => "Email",
	  	'telefono' => "Teléfono",
	  	'movil' => "Móvil",
		'empresa' => "Nombre Empresa",
		'CIF' => "CIF",
	  	'nivel' => "Nivel de Acceso",
	  	'creaccion' => "Fecha de Creacción",
	  	'caducidad' => "Fecha de Caducidad",
	  	'ultimo' => "Fecha Último Acceso",
		'asunto' => "Asunto",
		'msg' => "Mensaje",
		'msgOriginal' => "Mesaje original",
		'enviar' => "Enviar",
		'textoMail' => "Ha recibido un mensaje desde su zona privada de",
		'tituloMail' => "Mensaje recibido en su zona personal",
		'enviadoOK' => "Mensaje enviado con exito ...",
		'enviandoA' => "Enviando mensaje a"
	 );
?>