<?php

	/* Spanish language configuration */
	 $lang = array (
		'nombre' => "Nombre",
	  	'apellidos' => "Apellidos",
	  	'ciudad' => "Población",
		'municipio' => "Municipio",	  	
		'provincia' => "Provincia",		
	  	'pais' => "País",
		'empresa' => "Nombre Empresa",
		'buscar' => "Buscar",
		'sinResultados' => "Lo siento, no hay nada parecido en la Base de Datos",
		'numeroEncontrados' => "Número de usuarios encontrados",
		'desactivar' => "Desactivar todos",
		'seleccionar' => "Seleccionar todos",		
		'anadir' => "Añadir"
	 );
?>