<?php

	/* Spanish language configuration */
	 $lang = array (
		'cabecera' => "Plantilla Cabecera",
		'cuerpo' => "Plantilla Cuerpo",
		'pie' => "Plantilla Pie",
		'titulo' => "Título",		
		'remitente' => "Nombre Remitente",
		'emailRemitente' => "Email Remitente",
		'pruebas' => "Mail de Pruebas",
		'zonas' => "Zonas de contenido en el boletín",
		'guardar' => "guardar"
	 );
?>