<?php

	/* Spanish language configuration */
	 $lang = array (
	  	'nada' => "Lo siento, no hay nada parecido en la Base de Datos",
	  	'mandar' => "Mandar Mail",	
		'ficha' => "Ver Ficha",
		'nombre' => "Nombre y Apellidos",
		'mensaje' => "Enviar mensaje interno",
		'acciones' => "Acciones / Estado"		
	 );
?>