<?php

	/* Spanish language configuration */
	 $lang = array (
		'usuarios' => "usuarios",
		'todos' => "Todos",
		'importarN' => "Vincular (no se recomienda hacerlo en conjuntos de más de 20.000 en un solo paso)",
		'tramo' => "Tramo de vinculación",
		'anadir' => "Añadir"	
	 );
?>