<?php

	/* Spanish language configuration */
	 $lang = array (	 	
		'restaurar' => "Restaurar mensaje",
		'restaurado' => "Mensaje restaurado correctamente",
		'listado' => "Listado de mensajes en papelera",
		'acciones' => "Acciones / Estado",
		'asunto' => "Asunto",
		'de' => "Mensaje De",
		'fechaEnvio' => "Fecha de Envío",
		'sinMensajesPapelera' => "No tiene mensajes en la papelera de reciclaje"
	 );
?>