<?php

	/* Spanish language configuration */
	 $lang = array (
		'enviarSMSbloque' => "Enviar SMS en bloque",
		'editarSMSbloque' => "Editar SMS en bloque",
		'creditosDisponibles' => "Créditos disponibles",
		'creditosTotales' => "Créditos totales consumidos"
	 );
?>