<?php

	/* Spanish language configuration */
	 $lang = array (
		'texto' => "Texto del SMS",
		'remitente' => "Remitente",
		'borrarUsuario' => "Borrar usuario de la lista de SMS",
		'noUsuario' => "No hay usuarios seleccionados"
	 );
?>