<?php

	/* Spanish language configuration */
	 $lang = array (
		'errorPermisos' => "No tiene permisos para acceder a este área",
		'accesoIncorrecto' => "Error - Acceso incorrecto!",	
		'si' => "Sí",
		'no' => "No",
		'retocar' => "Retocar tamaño de la imagen",
		'titulo' => "Título",
		'texto' => "Texto",
		'imagen' => "Imagen",
		'anchoimagen' => "Ancho Imagen",
		'anchoampliado' => "Ancho Ampliado",
		'altoimagen' => "Alto Imagen",
		'altoampliado' => "Alto Ampliado",
		'alternativo' => "Texto Alternativo",	
		'alineacion' => "Alineación",
		'izquierda' => "Izquierda",
		'derecha' => "Derecha",
		'centrado' => "Centrado",
		'enlace' => "Enlace",
		'fichero' => "Fichero",
		'idVideoExterno' => "Id de Video en Youtube o Vimeo",
		'tipoReproduccion' => "Tipo de reproducción",
		'youtube' => "Youtube",
		'vimeo' => "Vimeo",
		'servidor' => "Reproducción propia",
		'video' => "Video en el servidor",
		'videofichero' => "Video",
		'anchovideo' => "Ancho Video",
		'altovideo' => "Alto Video",
		'latitud' => "Latitud (Norte)",
		'longitud' => "Longitud (Este)",		
		'centro' => "Coordenadas de punto central",
		'zoom' => "Zoom de Partida",
		'kml' => "Fichero KML o KMZ",
		'exigirvalidar' => "Exigir validar mensajes por responsable",
		'enviaraviso' => "Enviar aviso al usuario de respuestas",
		'enviaraviso2' => "Enviar aviso al responsable de cambios",
		'votacion' => "Permitir votación",
		'busqueda' => "Habilitar búsqueda de mensajes",
		'respuestas' => "Permitir respuestas a los mensajes",
		'maximo1' => "Permitir un máximo de un mensaje por usuario",
		'anonimoescritura' => "Foro anónimo escritura (Abierto mensajes a usuarios sin clave)",
		'anonimolectura' => "Foro anónimo lectura (Abierto lectura mensajes a usuarios sin clave)",
		'nivelescritura' => "Nivel exigido para Escritura",
		'nivellectura' => "Nivel exigido para Lectura",
		'configuracion' => "Configuración",		
		'tipo' => "Tipo",
		'urlamigable' => "URL Amigable (ejemplo: /OP-3216-opiniones-restaurante-la-posada.php)",
		'enviar' => "enviar",
		'titulo_amplia_contenido' => "Ampliar contenido",
		'titulo_amplia_contenido_editar' => "Editar ampliación de contenido",
		'configuraciones_foro' => "Configuraciones"
	 );
?>