<?php

	/* Spanish language configuration */
	 $lang = array (	 	
		'borrar' => "Borrar asignación como buscable",
		'general' => "Asignada a búsqueda general",
		'sinAsignaciones' => "Esta sección no tiene ninguna asignación de búsqueda",
		'asignar' => "Asignar Buscable para",
		'todos' => "Todo el Mundo",
		'enviar' => "enviar"
	 );
?>