<?php

	/* Spanish language configuration */
	 $lang = array (	 	
		'seguro' => "¿Estás seguro que deseas borrar la sección definitivamente junto con todos sus contenidos y todas sus subsecciones? ESTA ES UNA ACCIÓN PELIGROSA",
		'confirmar' => "Confirmar y Borrar",
		'cancelar' => "Cancelar y Volver"		
	 );
?>