<?php

	/* Spanish language configuration */
	 $lang = array (	 	
		'seguro' => "¿Estás seguro que deseas borrar el contenido definitivamente junto con todas sus ampliaciones y en todos los sitios en los que aparezca?",
		'borrar' => "borrar",
		'NOborrar' => "cancelar",
		'confirmar' => "Confirmar y Borrar",
		'cancelar' => "Cancelar y Volver"		
	 );
?>