<?php
	/* Spanish language configuration */
	 $lang = array (
		'errorPermisos' => "No tiene permisos para acceder a este área",
		'accesoIncorrecto' => "Error - Acceso incorrecto!",
		'estaUsted' => "Está usted en el contenido",
		'raiz' => "Raiz",
		'borrar' => "Borrar",
		'desactivar' => "Desactivar",
		'activar' => "Activar",
		'pendientes' => "Pendientes",
		'topArriba' => "Subir a la primera posición",
		'arriba' => "Subir una posición",
		'abajo' => "Bajar una posición",
		'topAbajo' => "Bajar a la última posición",
		'texto' => "Ampliación de tipo texto",
		'imagen' => "Ampliación de tipo imagen",
		'video' => "Ampliación de tipo video",
		'fichero' => "Ampliación de tipo fichero",
		'enlace' => "Ampliación de tipo enlace",
		'mapa' => "Ampliación de tipo Geolocalización",
		'mapaGoogle' => "Coordenadas no verificadas. Obtenidas directamente de google",
		'ruta' => "Ampliación de tipo ruta de Geolocalizaciones",
		'foro' => "Ampliación de tipo foro",
		'mensajes' => "mensajes",
		'editarMensajes' => "Editar mensajes del foro",
		'bloque' => "Ampliación de tipo bloque",
		'textoNoTitulo' => "Bloque de texto sin título",
		'imagenNoTitulo' => "Bloque de imagen sin título",
		'editarCampos' => "Editar campos adicionales",
		'ampliaciones' => "Ampliaciones"
	 );
?>