<?php

	/* Spanish language configuration */
	 $lang = array (		
		'errorPermisos' => "No tiene permisos para acceder a este área",
		'accesoIncorrecto' => "Error - Acceso incorrecto!",
		'borrarFichero' => "Borrar fichero",
		'enviar' => "enviar"
	 );
?>