<?php

	/* Spanish language configuration */
	 $lang = array (
		'errorPermisos' => "No tiene permisos para acceder a este área",
		'accesoIncorrecto' => "Error - Acceso incorrecto!",
		'tipo' => "Tipos de Formulario",
		'titulo' => "Título",
		'email' => "Email Destino",
		'eliminar' => "eliminar formulario",
		'editar' => "actualizar formulario"
	 );
?>