<?php

	/* Spanish language configuration */
	 $lang = array (	 			
		'titulo' => "Título",
		'fuente' => "Fuente RSS",
		'estado' => "Crear contenido en estado",
		'visible' => "Visible",
		'oculto' => "Oculto",
		'pendiente' => "Pendiente",
		'modo' => "Modo",
		'crear' => "Crear contenido",
		'visualizar' => "Visualizar contenido",
		'ampliable' => "Ampliable",
		'si' => "Si",
		'no' => "No",
		'syncMax' => "Sincronizaciones Máximas al día",
		'enviar' => "enviar"
	 );
?>