<?php

	/* Spanish language configuration */
	 $lang = array (
		'estaUsted' => "Está usted en la encuesta",
		'raiz' => "Raiz",
		'borrar' => "Borrar",
		'topArriba' => "Subir a la primera posición",
		'arriba' => "Subir una posición",
		'abajo' => "Bajar una posición",
		'topAbajo' => "Bajar a la última posición",
		'opcion' => "Opción"
	 );
?>