<?php

	/* Spanish language configuration */
	 $lang = array (
		'opcion' => "Opción",
		'imagen' => "Imagen",
		'anchoImagen' => "Ancho Imagen",
		'altoImagen' => "Alto Imagen",
		'alternativo' => "Texto Alternativo",
		'enviar' => "enviar"
	 );
?>