<?php

	/* Spanish language configuration */
	 $lang = array (	 			
		'titulo' => "Título / Mensaje",
		'valoracionFecha' => "Valoración / Fecha / Autor",
		'acciones' => "Acciones",
		'estrellaVacia' => "Valoración una estrella vacia",
		'estrellaLlena' => "Valoración una estrella llena",
		'editar' => "Editar",
		'fecha' => "Fecha",
		'borrar' => "Borrar",
		'validar' => "Validar",
		'validado' => "Validado",
		'usuario' => "Usuario",
		'ficha' => "Ver Ficha Usuario",
		'fichaNO' => "Ver Ficha Usuario No Disponible",
		'msgNO' => "NO EXISTEN MENSAJES"		
	 );
?>