<?php

	/* Spanish language configuration */
	 $lang = array (
		'errorPermisos' => "No tiene permisos para acceder a este área",
		'accesoIncorrecto' => "Error - Acceso incorrecto!",
		'ocultar' => "Ocultar información",
		'mostrar' => "Mostrar / Insertar información",
		'especialBuscadores' => "Campos especiales para buscadores",
		'especialPresentacion' => "Campos especiales de presentación del contenido",
		'titulo' => "Título",
		'breve' => "Texto",
		'texto' => "Texto",
		'imagen' => "Imagen",
		'imagenEditar' => "Añadir / Susistuir Imagen",
		'icono' => "Icono",
		'precioBI' => "Precio Base Imponible",
		'precioTAX' => "IVA %",
		'precioFinal' => "Precio Final",
		'tituloBuscadores' => "Título para buscadores",
		'descripcionBuscadores' => "Descripción para buscadores",
		'urlamigable' => "URL Amigable (ejemplo: restaurante-casa-paco)",
		'keywords' => "Palabras clave para buscadores",
		'notas' => "Notas de publicación",
		'plantilla' => "Plantilla",
		'tipo' => "Tipo de Contenido",		
		'fecha' => "Fecha (para noticias) - Formato aaaa-mm-dd (a -> Año, m -> Mes, d ->Día)",	
		'comportamiento' => "Comportamiento del contenido",
		'pulsarYPlantilla' => "Al pulsar abrir la plantilla con ampliaciones",
		'pulsarYImagen' => "Al pulsar abrir imagen/video emergente de primera ampliación",
		'pulsarYEnlace' => "Al pulsar abrir enlace emergente de primera ampliación",
		'pulsarYContenido' => "Al pulsar abrir enlace emergente con todas las ampliaciones",
		'noPulsable' => "No pinchable",
		'borrarImagen' => "Borrar imagen",
		'borrarIcono' => "Borrar icono",
		'fotoServidor' => "Imagen en servidor",
		'enviar' => "enviar"
	 );
?>