<?php

	/* Spanish language configuration */
	 $lang = array (	 			
		'titulo' => "Título",
		'enunciado' => "Enunciado de la encuesta",
		'fecha' => "Fecha tope para votar",		
		'enviar' => "enviar"
	 );
?>