<?php
	/* Spanish language configuration */
	 $lang = array (
		'errorPermisos' => "No tiene permisos para acceder a este área",
		'accesoIncorrecto' => "Error - Acceso incorrecto!",
		'si' => "Sí",
		'no' => "No",
		'retocar' => "Retocar tamaño de la imagen",	 
		'retocarIcono' => "Retocar tamaño del icono",
		'titulo' => "Título",
		'texto' => "Texto",
		'redireccionar' => "Redireccionar sección",
		'especialPresentacion' => "Campos especiales de presentación de la sección",
		'imagen' => "Imagen",
		'borrar' => "Borrar",
		'imagenEditar' => "Añadir / Sustituir Imagen",
		'anchoimagen' => "Ancho imagen",
		'altoimagen' => "Alto imagen",
		'icono' => "Icono",		
		'visibilidad' => "Visibilidad",
		'visible' => "Visible",
		'oculto' => "Oculto",
		'privado' => "Privado",
		'plantilla' => "Plantilla",
		'especialMicrosites' => "Campos especiales para crear Microsites",
		'dominio' => "Crear estructura de la miniweb. Dominio",
		'URLSeccion' => "Crear estructura de la miniweb. URL con ubicación de plantilla de sección",
		'URLContenido' => "Crear estructura de la miniweb. URL con ubicación de plantilla de contenido",
		'colorminiweb' => "Color Hexadecimal de la miniweb",
		'logominiweb' => "URL del logo para la miniweb",
		'ListadoFotoAncho' => "Ancho de la foto en los listados para la miniweb",
		'ListadoFotoAlto' => "Alto de la foto en los listados para la miniweb",
		'Analytics' => "Código javascript para google analytics en la miniweb",
		'paginacion' => "Número de contenidos por página",
		'desplegar' => "Mostrar / Desplegar",
		'especialBuscadores' => "Campos especiales para buscadores",
		'tituloBuscadores' => "Título para buscadores",
		'descripcionBuscadores' => "Descripción para buscadores",
		'keywords' => "Palabras clave para buscadores",
		'urlamigable' => "URL Amigable (ejemplo: restaurantes-en-aviles)",
		'indexable' => "Permitir a buscadores añadirlo a sus resultados de búsqueda",
		'prioridad' => "Prioridad para buscadores",
		'MP' => "Muy poco importante",
		'P' => "Poco importante",
		'M' => "Importancia media",
		'I' => "Importante",
		'MI' => "Muy importante",
		'enviar' => "enviar",
		'entorno' => "Entorno ya existente",
		'plantillaminiweb' => "Plantilla general de la miniweb",
		'plantillaseccionminiweb' => "Plantilla de la sección",
		'estructura' => "Cargar estructura de ejemplo",
		'datosEjemplo' => "Cargar datos de ejemplo",
		'numColumnas' => "Número de columnas",
		'titulo_nueva_seccion' => "Nueva sección",
		'tamano_imagenes' => "Tamaño de imágenes",
		'titulo_editar_seccion' => "Editar sección",
		'fechasPublicacion' => "Fechas publicación",
		'fechaComienzo' => "Fecha desde",
		'fechaFin' => "Fecha hasta"
	 );
?>