<?php

	/* Spanish language configuration */
	 $lang = array (	 	
		'seleccione' => "Seleccione el criterio por el cual quiere que se ordenen las secciones:<br/>NOTA: Se hará a nivel de base de datos y este orden se verá reflejado en la web",
		'alfabeticoSecciones' => "Secciones por orden alfabético",
		'alfabeticoContenidos' => "Contenidos por orden alfabético"
	 );
?>