<?php

	/* Spanish language configuration */
	 $lang = array (	 	
		'desactivar' => "Desactivar",
		'activar' => "Activar",
		'privado' => "Privado",
		'arriba' => "Subir una posición",
		'toparriba' => "Subir a primera posición",
		'abajo' => "Bajar una posición",
		'topabajo' => "Bajar a última posición",
		'editarIdioma' => "Editar sección en idioma",
		'anadirIdioma' => "Añadir sección en idioma",
		'editarIdioma' => "Editar en idioma",
		'suscrito' => "Suscrito a las siguientes secciones",
		'secciones_raiz' => "Secciones raiz"
	 );
?>