<?php

	/* Spanish language configuration */
	 $lang = array (	 	
		'errorPermisos' => "Error cod.: Usuario sin Permisos en esta sección",
		'estaUsted' => "Está usted en la sección",
		'raiz' => "Raiz",
		'contenidosPor' => "Contenidos Por Sección",		
		'desactivar' => "Desactivar",
		'activar' => "Activar",
		'privado' => "Privado",
		'arriba' => "Subir una posición",
		'toparriba' => "Subir a primera posición",
		'abajo' => "Bajar una posición",
		'topabajo' => "Bajar a última posición",
		'numeroResultados' => "Número de resultados",
		'numeroSuscritos' => "Número suscritos",
		'pendiente' => "Pendiente de Revisión",
		'pendientes' => "Pendientes",
		'vistas' => "Vistas",
		'clicks' => "Clicks",
		'encuesta' => "Encuesta",
		'codigo' => "Código",
		'formulario' => "Formulario",
		'calendario' => "Calendario",
		'webcam' => "Webcam",
		'rss' => "RSS",
		'ordenNormal' => "Orden establecido",
		'ordenAlfabetico' => "Orden alfabético",
		'ordenClicks' => "Orden de clicks",
		'ordenVistas' => "Orden de vistas",
		'ordenModificacion' => "Orden por modificación",
		'editarIdioma' => "Editar sección en idioma",
		'anadirIdioma' => "Añadir sección en idioma",
		'fechaCreacion' => "Fecha de creación",
		'fechaUltimaModificacion' => "Fecha de Última modificación",
		'verSeccion' => "Ver sección",
		'verContenido' => "Ver contenido",
		'secciones' => "Secciones",
		'editar_seccion' => "Editar sección",
		'contenidos' => "Contenidos",
		'elementos_especiales' => "Elementos especiales"
	 );
?>