<?php

	/* Spanish language configuration */
	 $lang = array (	 	
		'nota' => "Nota: Fecha como Año-Mes-Día. Ejemplo: 2039-05-28",
		'fechaFin' => "Fecha fin de suscripción",
		'suscribir' => "Suscribir"
	 );
?>